
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dnd-web
spec:
  selector:
    matchLabels:
      app: dnd-web
  replicas: 6
  template:
    metadata:
      labels:
        app: dnd-web
    spec:
      containers:
      - name: dnd-web
        image: kristjanoragnarsson/pypy-clust-test
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dnd-web
  labels:
    app: dnd-web
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30080
  selector:
    app: dnd-web